[package]
name = "funwithfailures"
version = "0.1.0"
authors = ["Diego Rubin <diegorubin@ciandt.com>"]
edition = "2018"

[dependencies]
telegram-bot = "0.6.3"
futures = "0.1.29"
tokio-core = "0.1.17"
reqwest = "0.9.20"
